[JmyL]
source             = notmuch://~/Mail/JmyL
query-map          = ~/.config/aerc/notmuch-queries
maildir-store      = ~/Mail/JmyL
multi-file-strategy = act-dir
check-mail         = 5m
check-mail-cmd     = ~/.local/bin/mail-sync-notify
check-mail-timeout = 5m

outgoing           = smtp://jmyl%40me.com@smtp.mail.me.com:587
outgoing-cred-cmd  = pass show mail/icloud/jmyl

from               = Sungsik Nam <jmyl@me.com>
aliases            = jmyl@me.com, jmyl@icloud.com

archive            = Archive
copy-to            = Sent Messages
postpone           = Drafts

folders = Conversations,Drafts,Flagged,Sent Messages,Archived
enable-folders-sort = true
folders-sort = Conversations,Drafts,Flagged,Sent Messages,Archived
